import networkx as nx

G = nx.Graph()
G.add_node(1, label="Luis", size=1)
G.add_node(2, label="Juan", size=2)
G.add_node(3, label="Daniel", size=3)
G.add_node(4, label="El colado 1", size=4)
G.add_node(5, label="El colado 2", size=5)
G.add_edge(1,2,weight=1)
G.add_edge(1,3,weight=2)
G.add_edge(1,4,weight=3)
G.add_edge(1,5,weight=4)
G.add_edge(2,3,weight=5)
G.add_edge(2,4,weight=6)
G.add_edge(2,5,weight=7)
G.add_edge(3,4,weight=8)
G.add_edge(3,5,weight=9)
G.add_edge(4,5,weight=10)
nx.write_gexf(G, "test.gexf")